name: Main

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Build
        run: go build .
      - name: Package
        run: |
          mkdir http-echo_
          mv http-echo http-echo_/
          cp LICENSE http-echo_/
          cp README.md http-echo_/
          mv http-echo_ http-echo
          tar zcf http-echo.tar.gz http-echo
          zip -r http-echo.zip http-echo
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            http-echo.tar.gz
            http-echo.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
